# Generated by Django 4.1.5 on 2023-02-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
