# Generated by Django 4.1.5 on 2023-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variations',
            field=models.ManyToManyField(to='products.variation'),
        ),
    ]
