# Generated by Django 4.1.5 on 2023-02-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created']},
        ),
    ]
