# Generated by Django 4.1.5 on 2023-02-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_coupen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='postal_code',
        ),
    ]
