# Generated by Django 4.1.5 on 2023-02-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='grand_total',
        ),
    ]
