# Generated by Django 4.1.5 on 2023-03-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_total_price_order_grand_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='grand_total',
            new_name='total_price',
        ),
    ]
