# Generated by Django 4.1.5 on 2023-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_order_order_status_wallet_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
