# Generated by Django 4.1.5 on 2023-02-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userotp_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'permissions': [('can_view', 'Can view user'), ('can_edit', 'Can edit user'), ('can_delete', 'Can delete user')]},
        ),
        migrations.RemoveField(
            model_name='signup',
            name='age',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='review',
        ),
    ]
