# Generated by Django 4.1.5 on 2023-02-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_signup_options_remove_signup_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
