# Generated by Django 4.1.5 on 2023-02-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
