# Generated by Django 4.1.5 on 2023-03-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance',
        ),
    ]
