# Generated by Django 4.1.5 on 2023-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
                ('valid_from', models.DateTimeField()),
            ],
        ),
    ]
