# Generated by Django 4.1.5 on 2023-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupn',
        ),
    ]
